---
driver:
  name: docker
  use_sudo: false
  privileged: true

verifier:
  name: inspec
  format: doc

provisioner:
  name: salt_solo
  log_level: debug
  require_chef: false
  formula: zookeeper

platforms:
  - name: ubuntu-16.04
    driver_config:
      provision_command:
        - apt-get update && apt-get install -y netcat-openbsd locales && locale-gen en_US.UTF-8
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
  - name: centos-7
    driver_config:
      image: centos:7
      provision_command:
        - yum -y install initscripts nmap-ncat
      platform: rhel
      run_command: /sbin/init
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    provisioner:
      vendor_path: vendor/sun-java-formula
      state_top:
        base:
          '*':
            - sun-java
            - sun-java.env
            - zookeeper
            - zookeeper.server
      pillars:
        top.sls:
          base:
            '*':
              - zookeeper
              - sun-java
        sun-java.sls:
          java:
            version_name: jdk1.8.0_131
            source_url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.tar.gz
            source_hash: 62b215bdfb48bace523723cdbb2157c665e6a25429c73828a32f00e587301236
        zookeeper.sls:
          zookeeper:
            version: 3.4.10
            source_md5: e4cf1b1593ca870bf1c7a75188f09678
            config:
              port: 2181
